### ISSUE TITLE
Got a question for you.

### ISSUE THREAD

**Issue by chrobione** [c7a1/BrythonFiveM#1]
I am curious what fs_freeroamEnhanced is?

This looks ya missed some of the important reading on the README.md
specifically this part here:

`DO NOT RENAME a resource. Retain the authenticity of it. Everything is designed the way it is for a reason. Do not go behind someone else and redo what someone took the time and effort to do to make everything work.`

We have this as well :
[Contributing.MD](https://github.com/FiveM-Scripts/fs_freeroam/blob/master/CONTRIBUTING.MD)

I am curious what your intentions are.

**Comment by davedumas0** [comment]
stealing is NOT COOL

**Comment by c7a1** [comment]
Hello,

My intentions is to rewrite all the backend code to essentialmode and
fs_freeroam to make it more modular, and everything in the folders are just
temporary names.

Currently I am running into asynchronous issues and are working on a
solution. I have no intention of removing anyone's effort as names/aliases
will be present in all code once completed.

If you can provide the license used and I am breaking said license, I will
remove any code that is not mine and develop my own.

Thank you.


On May 23, 2017 6:37 PM, "Chrobi" <notifications@github.com> wrote:

I am curious what fs_freeroamEnhanced is?

This looks ya missed some of the important reading on the README.md
specifically this part here:

DO NOT RENAME a resource. Retain the authenticity of it. Everything is
designed the way it is for a reason. Do not go behind someone else and redo
what someone took the time and effort to do to make everything work.

I am curious what your intentions are.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/c7a1/BrythonFiveM/issues/1>, or mute the thread

**Comment by ghermans** [comment]
> My intentions is to rewrite all the backend code to essentialmode and fs_freeroam to make it more modular, and everything in the folders are just temporary names.

1.Essentialmode has no license so this means you can use it and fork it. [more info here](https://choosealicense.com/no-license/)
2. regarding freeroam, if you want to make it more modular you could just fork the project, and make PR requests, instead doing what you are doing now...
and 3.
![disclaimerknipsel](https://cloud.githubusercontent.com/assets/1594411/26384119/4fe5c144-4037-11e7-9212-1bc4cb1ca0c4.PNG)

is it really that hard to read?

**Comment by chrobione** [comment]
So your are missing the most important part of the [Contrib](https://github.com/c7a1/BrythonFiveM/blob/master/resources/fs_freeroamEnhanced/CONTRIBUTING.MD)
Please take a moment to read it. 

Personally I feel like you are in direct violation of our request for your use of our code. Especially the part that I have already pointed out to you.  

`DO NOT RENAME a resource. Retain the authenticity of it. Everything is
designed the way it is for a reason. Do not go behind someone else and redo
what someone took the time and effort to do to make everything work.`

What you have done is basically a "FU" to us.

If you want to help make it better, please make PR's to our repos and come to our discord and see what is in the pipe.

**Comment by c7a1** [comment]
Complied and apologized. Will follow the rules of the owners of this code.
